### ISSUE TITLE
Chat Interface

### ISSUE THREAD

**Issue by nikhil9302** [iiitkottayam/InternshipPortal-Frontend#10]
**Is your feature request related to a problem? Please describe.**
Need to build a Chat interface 

**Describe the solution you'd like**
Using Django channels.
Basic Features: A chat screen similar like LinkedIn

**Describe alternatives you've considered**
Socket.io could be an alternative if we want to implement it from scratch. Any other suggestions, ask the maintainers.

**Additional context**
Design Interface: [Figma link](https://www.figma.com/file/lgyvNLtzDU8PvsecC0hKfX/Design)

**Comment by shashank1503-cipher** [comment]
No need for this currently now
